.github/workflows/ci.yml
examples/squaring/modules/go.mod
modules/go.mod

Validate that cosmwasm-schema Types has not drifted.
> This PR also update `go.mod` to the latest version.

chore: verify cosmwasm-schema has not drifted

---

crates/bvs-vault-router/Cargo.toml
crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/msg.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

Prior to this PR, there's no good way to get all the delegated vault given a particular operator x. 
This PR attempt to provide a query message that given an operator, would return a paginated list of vaults that the specified operator is delegating. 
The most notable in this PR. (Reviewing the codes in order by following order of bullet points is recommended)
- One new state `Map<(&Addr, &Addr), ()>`. Composite key tuple `.0` is ref to operator address and `.1` is ref to vault contract address. And the value is empty tuple.
- Currently the only place this state get mutated is in `setVault()` execute message handler.
- `setVault()` , prior to this PR, do the query msg to the vault only if whitelist is true to check if the vault set its router the same as `env.contract.address`. But …

feat: support get vaults by operator in bvs-router

---

.github/workflows/ci.yml
crates/bvs-library/src/testing/account.rs
crates/bvs-pauser/src/contract.rs
crates/bvs-pauser/src/msg.rs
crates/bvs-pauser/tests/integration_tests.rs
crates/bvs-registry/src/state.rs
crates/bvs-registry/tests/integration_test.rs
crates/bvs-slash-manager/src/contract.rs
crates/bvs-vault-router/tests/integration_test.rs

Run `cargo clippy --fix` before `cargo clippy -- -D warnings` to ensure what can be automatically fixed should be fixed. For consistency.
Closes SL-437

chore: run `cargo clippy --fix` on CI

---

.github/workflows/ci.yml

Allow clippy to run when it's dirty, ideally we don't need this as we should not have unstagged changes. But this would make DX very difficult.

chore: allow clippy --fix to run when dirty

---

packages/cosmwasm-optimizer/Dockerfile

With the removal of deprecated components/contracts using libraries that is not pure, we don't need clang anymore.
> We will need this to verify contracts on explorers.
Closes SL-470

chore: remove clang in cosmwasm-optimizer

---

crates/bvs-library/src/testing/contract.rs
crates/bvs-registry/src/contract.rs
crates/bvs-registry/src/lib.rs
crates/bvs-registry/src/msg.rs
crates/bvs-registry/src/state.rs
crates/bvs-registry/src/testing.rs
crates/bvs-registry/tests/integration_test.rs
modules/cosmwasm-schema/registry/schema.go
packages/cosmwasm-schema/registry.d.ts

To support support look up of registration status at a specific height for Operator <-> Service relationship, migrate from `Map<...>` to `SnapshotMap<...>`. This will allow query of `StatusAtHeight`, given operator, service and blockheight.
Migrating data is not needed as `SnapshotMap` uses `Map` with the same namespace.
https://github.com/CosmWasm/cw-storage-plus/blob/b06e11931a19e9a75204139734176a1c5513943e/src/snapshot/map.rs#L42-L52
This migration will also means that the current state of `REGISTRATION_STATUS` will be the default state when `StatusAtHeight` query is used for height before migration. For instance, migration happens at block 200 and Operator1 and Service1 is in Active status. When queried at height 1, the status of Operator1 and Service1 will be Active.
Closes SL-443

feat: migrate registry REGISTRATION_STATUS to use SnapshotMap

---

crates/bvs-library/src/lib.rs
crates/bvs-library/src/time.rs
crates/bvs-registry/src/contract.rs
crates/bvs-registry/src/error.rs
crates/bvs-registry/src/lib.rs
crates/bvs-registry/src/msg.rs
crates/bvs-registry/src/state.rs
crates/bvs-registry/tests/integration_test.rs
modules/cosmwasm-schema/registry/schema.go
packages/cosmwasm-schema/registry.d.ts

Main changes:
- `ExecuteMsg::EnableSlashing` - service enable / update slashing condition
- `ExecuteMsg::DisableSlashing` - service disable slashing condition
- `ExecuteMsg::OperatorOptInToSlashing` - active operator opt in to service slashing condition
- `QueryMsg::SlashingRegistry` - retrieve service's slashing condition
- `QueryMsg::IsOperatorOptedInToSlashing` - check if operator is opted into service slashing condition
Notable changes:
- Introduced small time helper lib in `bvs-library` for more readable time (in seconds)
- Once slashing is enabled, new Operator <-> Service active registration will **AUTOMATICALLY** opt in operator into the slashing condition.
- With SL-471, increasing/decreasing counter is coupled tightly with `set_registration_status` fn.
TODO:
Closes SL-464
Closes …

feat: enable/disable slashing and opt in to slashing

---

crates/bvs-registry/src/msg.rs
crates/bvs-registry/src/state.rs
modules/cosmwasm-schema/registry/schema.go
packages/cosmwasm-schema/registry.d.ts

Fully document the registration status for extra verbosity.
Closes SL-472

chore: document Registration status

---

crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-base/src/offset.rs
crates/bvs-vault-cw20/src/contract.rs

See https://github.com/satlayer/satlayer-bvs/pull/544#issuecomment-2834799655 for why we need it.
This PR separates the storage logic and offset logic from `VirtualOffset` into `VirtualOffset` to just handle offset without storage or mutating checked sub/add.
`TotalShares` will become `VirtualOffset`, but with `TOTAL_SHARES` storage features, `checked_add_shares` and `checked_sub_shares` implemented.

chore: separate storage logic from `VirtualOffset` into `TotalShares`

---

crates/bvs-library/package.json
crates/bvs-pauser/package.json
crates/bvs-registry/package.json
crates/bvs-vault-cw20/src/contract.rs
crates/bvs-vault-cw20/tests/integration_test.rs
crates/bvs-vault-router/package.json
pnpm-lock.yaml

Due to `dev-dependency` circular setup, added `--no-verify` such that cargo publish doesn't build before publishing.

chore(release): cargo publish without verification

---

.github/workflows/release.yml

To conform to crates release versioning/label.

chore(release): use 0.0.0-main.run_number for crates release

---

crates/Cargo.lock
crates/bvs-vault-cw20-tokenized/Cargo.toml

Fix missing `description.workspace = true` for `bvs-vault-cw20-tokenized`.

chore: description for bvs-vault-cw20-tokenized

---

crates/bvs-pauser/src/state.rs
crates/bvs-registry/src/state.rs
crates/bvs-vault-factory/src/state.rs
crates/bvs-vault-router/src/state.rs
examples/squaring/contract/src/state.rs

Use `pub(crate) const` and `pub(crate) fn` for most functions and state variables to limit the visibility of these crates.
Closes SL-486

chore: use `pub(crate)` in `state.rs`

---

crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-bank/tests/integration_test.rs
crates/bvs-vault-cw20-tokenized/src/contract.rs
crates/bvs-vault-cw20-tokenized/tests/integration_test.rs
crates/bvs-vault-cw20/src/contract.rs
crates/bvs-vault-cw20/tests/integration_test.rs

Use `Timestamp` to compute unlock timestamp to avoid extra type conversion.
Closes SL-480

chore: use Timestamp type to compute time

---

.github/workflows/release.yml
packages/cli/package.js

For cli releases, reference the main package version and set it for all the sub packages.

chore(release): set cli release versions manually

---

packages/cli/package.js

`workspace:*` should be set to actual versions.

chore(release): replace workspace:* versions

---

packages/cli/README.md
packages/cli/package.js

```js
bin: {
satlayer: "satlayer",
}
```

chore: set bin satlayer for platform specific bins

---

modules/cosmwasm-cli/cmd/rewards.go

update rewards-cli to only 1 required params. Pass in the full file path to `distribution.json` instead for easier cli

chore: refactor rewards cli

---

modules/cosmwasm-cli/package.json

Disable CGO, run Go CLI without any external dependencies.

chore: CGO_ENABLED=0 for CLI

---

packages/testcontainers/src/container.ts
packages/testcontainers/src/satlayer.test.ts
packages/testcontainers/src/satlayer.ts

- `fund` address with coins
- `contracts.router.execute` and `.query` for ease for dev testing
- `contracts.registry.execute` and `.query` for ease for dev testing

feat: utility methods for testcontainers

---

crates/Cargo.lock
crates/Cargo.toml
crates/bvs-guardrail/Cargo.toml
crates/bvs-guardrail/README.md
crates/bvs-guardrail/package.json
crates/bvs-guardrail/src/bin/schema.rs
crates/bvs-guardrail/src/contract.rs
crates/bvs-guardrail/src/error.rs
crates/bvs-guardrail/src/lib.rs
crates/bvs-guardrail/src/msg.rs
crates/bvs-guardrail/src/state.rs
crates/bvs-guardrail/src/testing.rs
crates/bvs-guardrail/tests/integration_test.rs
crates/bvs-vault-router/src/state.rs
crates/crates.iml
docs/app/contracts/_meta.ts
docs/app/contracts/guardrail/page.md
modules/cosmwasm-schema/generate.mjs
modules/cosmwasm-schema/guardrail/schema.go
modules/cosmwasm-schema/package.json
packages/cosmwasm-schema/generate.mjs
packages/cosmwasm-schema/guardrail.d.ts
packages/cosmwasm-schema/package.json
pnpm-lock.yaml

Changes:
notable changes:
- ~~in cw3, the `proposal_id` used is assigned on proposal creation and is an increasing number. However, for this contract the `proposal_id` has been updated to be the same as `slashing_id` instead which is 32 byte hex string.~~
- ~~Due to the changes above, `listProposal` query msg has to be modified because it cannot be paginated by the id but instead by specifying `skip` and `take` which may not be in the order of creation (may need to fix ??) . Also `reverseProposal` cannot be supported, thus removed.~~
- ~~Due to the changes to `proposal_id`, also note that there cannot be the same `slashing_id` used.~~
- the response emitted by the execute have been modified to put the attributes under a new event. This is to closely resemble all of our core contracts as …

feat: bvs-guardrail

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

- Store `Service` that initiated the slashing request in `SlashingRequest` struct.
- Changed the hashing fn to not require extra "service" address as it is now part of the struct.
- Impl `partialEq` for `SlashingRequestStatus` and `u8` so that they can be compared without explicit conversion

feat: store service in slash request + impl partialEq

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/msg.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

Cancel slashing request for operators that have resolved the issues. About `CancelSlashing`, can refer [doc](https://build.satlayer.xyz/getting-started/slashing#cancel-slashing-resolved).
Closes SL-474

feat: cancel resolved slashing request

---

crates/bvs-library/src/testing/contract.rs
crates/bvs-vault-router/tests/integration_test.rs

uses `app.execute_contract(...)` because this fn uses `app.execute(...)` + parsing protobuf data back to its original form. This will allow `response.set_data(...)` to be used and returned properly.
Closes SL-502

fix: use app.execute_contract instead

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs

Slashing request payload has an upgrade to include a status field that represent status of a given slash request - Pending, Locked, Finalized, Canceled. 
With that, we discovered the data state are now a bit more complex with the need to sync the status appropriately. For example, slash is pending sitting idle for a long time beyond expiry date. Although the state may represent as pending this is effectively expired slash request that should be canceled. 
As mentioned above these path are slightly more complex, thus an incentive to document them with comments. But the  permutation of scenarios and nuances in code such as map `SLASHING_REQUEST_IDS` entry is removed when cancel or finalized but the map `SLASHING_REQUESTS` entry's status are being updated rather than a delete - prove too …

fix: implicit slash cancellations 

---

packages/testcontainers/src/container.ts
packages/testcontainers/src/satlayer.ts

return `guardrail` contracts in testcontainers, needed for examples
added `generateAccount` to generate new valid address for a given seed

chore: return guardrail in testcontainers contracts

---

docs/app/getting-started/slashing/page.mdx

chore(docs): inconsistent resolution_window value

---

modules/cosmwasm-cli/cmd/rewards.go

- update rewards proof cli command to return proof in hex string instead of b64
- rename `claim_reward_proof` to `claim_rewards_proof`

chore: update rewards proof to return hex string

---

packages/cli/package.js

- Node 20.18.2 will throw an error.
- Node 20.19.0 will show a warning, then run as ESM.
Let's just use CommonJS.

chore: use commonjs for package.js

---

contracts/LICENSE
contracts/foundry.toml
contracts/script/Deployment.s.sol
contracts/src/EmptyImpl.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/src/SLAYVault.sol
contracts/src/SLAYVaultFactory.sol
contracts/test/MockERC20.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYVault.t.sol
contracts/test/TestSuite.sol

Set the default consistent with `pragma solidity` for all contracts. 
Updated the license to match the root directory.
Closes SL-551

chore: set default solc version

---

contracts/src/SLAYRouter.sol
contracts/src/SLAYVault.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYVault.t.sol
contracts/test/TestSuite.sol

Add `modifier whenNotPaused` to SLAYVault, which sources paused state from SLAYRouter. SLAYVault doesn't enforce its own pause state, but relies on the SLAYRouter to manage the pause state. If the SLAYRouter is paused, all operations marked with this modifier will revert with `EnforcedPause`.
Add `modifier whenWhitelisted` to SLAYVault. If the SLAYVault is not whitelisted on SLAYRouter, all operations marked with this modifier will revert with `ExpectedWhitelisted`.
Closes SL-544

feat: SLAYRouter whitelist and pausable implementation

---

contracts/src/SLAYVaultFactory.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYVault.t.sol
contracts/test/SLAYVaultFactory.t.sol
contracts/test/TestSuite.sol

- Implement `_checkOperator` in SLAYVaultFactory.
Closes SL-556
Also, this PR removes `newVault()` helper. This was quite an opinionated setup; it's better for downstream tests to create a vault without using helpers.

feat: implement _checkOperator for VaultFactory

---

contracts/script/Deployment.s.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/src/SLAYVault.sol
contracts/src/SLAYVaultFactory.sol
contracts/test/TestSuite.sol

Use OZ `Core.validateImplementation` and `Core.validateUpgrade` to validate implementation and upgrade before deployment.
Closes SL-576

chore: use OZ validateImplementation and validateUpgrade for scripts before deployment

---

contracts/script/Deployment.s.sol
contracts/src/InitialImpl.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/src/SLAYVault.sol
contracts/test/InitialImpl.t.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/SLAYRouter.t.sol
contracts/test/TestSuite.sol

Include `PausableUpgradeable` in `InitialImpl` to allow contracts to be paused during initial deployment. Remove `initialize2` and `initialize` from `SLAYRouter` and `SLAYRegistry` since they will be initialized only from `InitialImpl`, doing so to prevent confusion.
Also, add updated a bunch of tests to test for `whenNotPaused` state.
Closes SL-583

feat: move pausability to `InitialImpl`

---

contracts/src/SLAYVault.sol
contracts/test/SLAYVault.t.sol

Only allow these entities to request withdrawal on behalf of owner:
1. owner
2. owner's approved operator
3. owner's approved operator's approved operator (with appropriate allowance from owner)
Closes SL-602

chore: only allow self or operator to withdraw

---

contracts/src/Relationship.sol
contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

Refactor `enableSlashing(address)` to `approveSlashingFor(address)` for better clarity of method.

chore: rename enableSlashing(address) to approveSlashingFor(address)

---

contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

Changes:
1. move `_withdrawalDelay` state into `Operator` struct
2. introduce 2 mappings `_operatorsActiveRelationships` and `_servicesActiveRelationships`
3. removed `activeOperatorsCount` and `activeServicesCount` in favour of the above
4. add checks whenever, `operator` or `service` changes their withdrawal delay
5. set operator's default withdrawal delay on first registration `operator.withdrawalDelay = DEFAULT_WITHDRAWAL_DELAY`
Closes SL-545

chore: allow variable withdrawal delay for service and operator

---

contracts/script/Deployment.s.sol
contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYRouterV2.t.sol
contracts/test/TestSuiteV2.sol

- Set max vaults allowed per operator. Enforced with `EnumerableSet.AddressSet`. Stored in     a operator mapping: `mapping(address operator => EnumerableSet.AddressSet)`
- The vault max count can be updated by the owner, but only with a higher value.
Closes SL-611

feat: max vaults per operator

---

contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYSlashingV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYVaultV2.t.sol

1. rename to `lockSlashing` for vault's fn
2. update the vault events as well to `SlashingLocked`

chore: refactor lock slashing

---

contracts/script/Deployment.s.sol
contracts/src/SLAYBase.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/src/interface/ISLAYVaultFactoryV2.sol
contracts/test/SLAYVaultFactoryV2.t.sol
contracts/test/TestSuiteV2.sol

As titled, this PR cleans up the documentation and testing for SLAYVaultFactory.
For consistency, we will use `SLAYBase` for `SLAYVaultFactory`.
I've also updated "Slaynet.s.sol" script to `Deployment.s.sol` so that what we deploy into testnet is the same as mainnet to prevent any unnecessary drift in code.
Closes SL-633

chore: document and refactor SLAYVaultFactory

---

contracts/src/SLAYRegistryV2.sol
contracts/src/interface/ISLAYRegistryV2.sol
contracts/test/SLAYRegistryV2.t.sol

Main changes: renames `struct Operator` and `struct Service` to `struct OperatorEntry` and `struct ServiceEntry` so that there isn't any weird collision with `address operator` and `struct Operator`. Hence, with this PR, I've also renamed `Service storage service` to `ServiceEntry storage serviceEntry` and related.
As per the title, this PR includes changes to Registry documentation and test refactoring/addition.
Closes SL-631

chore: document and refactor SLAYRegistry

---

contracts/src/MerkleProof.sol
contracts/test/MerkleProof.t.sol
crates/bvs-rewards/src/merkle.rs
crates/bvs-rewards/src/testing.rs
crates/bvs-rewards/tests/integration_test.rs
modules/cosmwasm-cli/cmd/rewards.go

Notable Changes:
1. Sorting of merkle leaves is turned off - no extra security value as we don't need to prove non-membership.
2. Standardise all merkle hashing to use `keccak256` inline with solidity's version
Closes SL-627
Closes SL-628

chore: update merkle rewards hashing to keccak256

---

.github/dependabot.yml

As titled, it should be updated together.

chore(deps): update @openzeppelin dependencies together

---

contracts/src/SLAYVaultV2.sol
contracts/test/RelationshipV2.t.sol
contracts/test/SLAYRouterV2.t.sol
contracts/test/SLAYVaultFactoryV2.t.sol

`forge build` will create 4 warnings that cannot be fixed, as they're required to fail as described in https://eips.ethereum.org/EIPS/eip-7540#reversion-of-preview-functions-in-async-request-flows
```
Compiler run successful with warnings:
Warning (5740): Unreachable code.
--> node_modules/@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC4626Upgradeable.sol:255:9:
|
255 |         _withdraw(_msgSender(), receiver, owner, assets, shares);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning (5740): Unreachable code.
--> node_modules/@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC4626Upgradeable.sol:257:9:
|
257 |         return shares;
|         ^^^^^^^^^^^^^
Warning (5740): Unreachable code.
--> …
```

chore: document behavior of warnings in ERC4626Upgradeable

---

contracts/src/SLAYBase.sol
contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRewardsV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/test/SLAYBase.t.sol
contracts/test/SLAYVaultFactoryV2.t.sol

chore: refactor SLAY contracts to use ownable2step

---

contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/test/SLAYVaultFactoryV2.t.sol

Remove redundant whenNotPaused: 
- for registerOperatorToService inner state transition already has this modifier
- for create(IERC20 asset, address operator...)` this is only callable by owner so it's already a protected state 
Closes SL-672

chore: cleanup whenNotPaused usage

---

contracts/script/SLAYNet.s.sol
contracts/src/SLAYRewardsV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultV2.sol
contracts/test/MerkleProof.t.sol
contracts/test/SLAYRouterV2.t.sol
contracts/test/SLAYVaultV2.gas.t.sol

- Add non-reentrant for functions in SLAYRouter. We don't use the Transient (eip-1153) to support older evm versions.
- Add more documentation to describe contract safety behavior 
- Introduce a new `initializeAll` function for SLAYRouter for Upgrade safe checks.
- Refactor some parts of the contract to improve overall safety.
Closes SL-658, SL-670

chore: overall contract safety refactoring

---

contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYRegistryV2.sol
contracts/test/SLAYRouterV2.t.sol
contracts/test/SLAYVaultV2.t.sol

Document some parameter usage on the contracts.
For `SLAYVaultV2.lockSlashing(uint256)`, when the amount is zero, an if condition check has been added to prevent it from being called.
Also, added more tests.
Closes SL-669, SL-674

chore: test and document params usage for contracts

---

contracts/src/SLAYRegistryV2.sol

Save about a negligible (at current eth prices) amount of gas 30-100 on avg. (stats tracked at when contract is not fat with states).
Closes SL-678

chore: bind _msgSender() to address and remove single use var binding in loop

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol

chore: add getSlashingRequestId to SLAYRouter

---

packages/testcontainers/src/evm-contracts.test.ts
packages/testcontainers/src/evm-contracts.ts

1. Fix initVault producing same vault address for different operators
2. move oracle and mockPyth to private and introduce getters for type safety

chore: fix initVault + add getter for oracle
