satlayer/satlayer-bvs

crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-bank/tests/integration_test.rs
crates/bvs-vault-base/src/router.rs
crates/bvs-vault-cw20/tests/integration_test.rs

Unsatisfied clippy rules were getting into the main. Not sure why. But this is polluting other tickets in their PR when the PR attempt to fix clippy rules. The goal of this PR is to isolate the clippy fix to keep other ticket and their PR sane for reviewers.

feat: clippy fixes for all vault stacks - base, bank, cw20

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/tests/integration_test.rs

chore: fixes and document migration and set_vault

---

docs/app/architecture/_meta.ts
docs/app/architecture/operators/page.mdx
docs/app/architecture/rewards/page.md
docs/app/architecture/rewards/page.mdx
docs/app/architecture/services-and-operators/page.mdx
docs/app/architecture/services/page.mdx
docs/app/architecture/slashing/page.md
docs/app/architecture/slashing/page.mdx
docs/app/layout.tsx

chore: architecture docs for  service and operators

---

crates/bvs-library/src/lib.rs
crates/bvs-library/src/storage.rs
crates/bvs-registry/src/contract.rs
crates/bvs-registry/src/msg.rs
crates/bvs-registry/src/state.rs
crates/bvs-registry/tests/integration_test.rs
modules/cosmwasm-schema/registry/schema.go
packages/cosmwasm-schema/registry.d.ts

feat: refactor snapshot to use timestamp instead of height

---

.github/workflows/release.yml
crates/Cargo.toml
crates/bvs-library/package.json
crates/bvs-pauser/package.json
crates/bvs-registry/package.json
crates/bvs-vault-router/package.json
pnpm-lock.yaml
turbo.json

Publish `bvs-*` crates that are needed to integrate with SatLayer.
Closes SL-478

feat: publish bvs-* crates

---

.github/workflows/release.yml

chore(release): include build metadata for crates

---

turbo.json

chore(release): include CARGO_REGISTRY_TOKEN in cargo:publish

---

crates/bvs-library/Cargo.toml
crates/bvs-pauser/Cargo.toml
crates/bvs-registry/Cargo.toml
crates/bvs-rewards/Cargo.toml
crates/bvs-vault-bank/Cargo.toml
crates/bvs-vault-base/Cargo.toml
crates/bvs-vault-cw20/Cargo.toml
crates/bvs-vault-factory/Cargo.toml
crates/bvs-vault-router/Cargo.toml

chore(release): add missing description for crates

---

.github/workflows/release.yml
crates/Cargo.lock
crates/bvs-vault-factory/Cargo.toml

chore(release): remove --dry-run

---

crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-bank/tests/integration_test.rs
crates/bvs-vault-base/src/msg.rs
crates/bvs-vault-cw20-tokenized/src/contract.rs
crates/bvs-vault-cw20-tokenized/tests/integration_test.rs
crates/bvs-vault-cw20/src/contract.rs
crates/bvs-vault-cw20/tests/integration_test.rs
modules/cosmwasm-schema/vault-bank/schema.go
modules/cosmwasm-schema/vault-cw20-tokenized/schema.go
modules/cosmwasm-schema/vault-cw20/schema.go
packages/cosmwasm-schema/vault-bank.d.ts
packages/cosmwasm-schema/vault-cw20-tokenized.d.ts
packages/cosmwasm-schema/vault-cw20.d.ts

chore: remove slashing from vault info

---

.github/workflows/release.yml

chore(release): manually order and publish crates

---

.github/workflows/release.yml
crates/Cargo.lock
crates/Cargo.toml
crates/README.md
crates/bvs-multi-test/Cargo.toml
crates/bvs-multi-test/README.md
crates/bvs-multi-test/src/lib.rs
crates/bvs-vault-cw20-tokenized/README.md
crates/crates.iml
docs/app/contracts/_meta.ts
docs/app/contracts/multi-test/page.md
docs/app/contracts/vault-cw20-tokenized/page.md

BVS Multi Test is a testing utility for the SatLayer ecosystem.
It provides a convenient way to bootstrap all the necessary contracts for testing services in the BVS ecosystem.
This PR also adds the missing docs for `crates/bvs-vault-cw20-tokenized/README.md`.
Closes SL-487

feat: bvs-multi-test

---

crates/bvs-registry/README.md
docs/app/developers/cosmwasm/integrating/page.mdx
docs/app/developers/examples/_meta.ts
examples/squaring/README.mdx
examples/squaring/contract/Cargo.lock
examples/squaring/contract/Cargo.toml
examples/squaring/contract/tests/integration_test.rs

Update the `Integrating with SatLayer` docs.
Closes SL-458

chore(docs): Integrating with SatLayer

---

docs/app/developers/overview/page.mdx
docs/app/developers/program-agnostic/_meta.ts
docs/app/developers/program-agnostic/go/page.mdx
docs/app/developers/program-agnostic/javascript/page.mdx
docs/app/developers/program-agnostic/page.mdx

Documenting more about the program-agnostic nature of BVS.
Closes SL-488

chore(docs): program-agnostic docs

---

crates/README.md

chore(docs): contract addresses

---

crates/bvs-vault-bank-tokenized/README.md
crates/bvs-vault-bank-tokenized/src/contract.rs
crates/bvs-vault-bank-tokenized/src/msg.rs
crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-base/src/msg.rs
crates/bvs-vault-cw20-tokenized/src/contract.rs
crates/bvs-vault-cw20-tokenized/src/msg.rs
crates/bvs-vault-cw20/src/contract.rs
docs/app/contracts/_meta.ts
docs/app/contracts/vault-bank-tokenized/page.md
modules/cosmwasm-schema/vault-bank-tokenized/schema.go
modules/cosmwasm-schema/vault-bank/schema.go
modules/cosmwasm-schema/vault-cw20-tokenized/schema.go
modules/cosmwasm-schema/vault-cw20/schema.go
packages/cosmwasm-schema/vault-bank-tokenized.d.ts
packages/cosmwasm-schema/vault-bank.d.ts
packages/cosmwasm-schema/vault-cw20-tokenized.d.ts
packages/cosmwasm-schema/vault-cw20.d.ts

chore(docs): missing docs, typo in docs and fix broken links

---

docs/app/layout.tsx

chore: remove wip banner

---

.github/workflows/ci.yml
.github/workflows/docker-cache.yml
.github/workflows/release.yml
examples/squaring/contract/package.json
package.json
packages/cosmwasm-optimizer/README.md
packages/cosmwasm-optimizer/bin.js
packages/cosmwasm-optimizer/package.json
packages/cosmwasm-schema/README.md
pnpm-lock.yaml
turbo.json

A command-line tool that simplifies the process of optimizing CosmWasm smart contracts for deployment. This tool wraps the official CosmWasm optimizer Docker image, providing an easy-to-use interface for building production-ready WebAssembly (Wasm) binaries.
Closes SL-497

feat: cosmwasm-optimizer

---

examples/package.json
examples/squaring/README.mdx
examples/squaring/contract/src/contract.rs
examples/squaring/contract/src/msg.rs
examples/squaring/contract/src/state.rs
examples/squaring/contract/tests/integration_test.rs

chore(examples): squaring contract

---

packages/cli/postinstall.js

fix: postinstall cli wrong package

---

.github/dependabot.yml
examples/squaring/service/package.json
examples/squaring/service/src/squaring.test.ts
package.json
packages/cli/README.md
packages/cosmwasm-optimizer/package.json
packages/cosmwasm-schema/package.json
packages/testcontainers/package.json
packages/testcontainers/src/index.ts
packages/testcontainers/src/satlayer.test.ts
packages/testcontainers/src/satlayer.ts
packages/testcontainers/tsconfig.json
pnpm-lock.yaml

Introduce `@satlayer/testcontainers` for testing SatLayer Core in NodeJS environment.
Closes SL-141

feat: @satlayer/testcontainers for nodejs

---

examples/squaring/service/src/squaring.test.ts
packages/testcontainers/package.json
packages/testcontainers/src/satlayer.test.ts
packages/testcontainers/src/satlayer.ts
pnpm-lock.yaml

Basic test utility for `@satlayer/testcontainers`
- `fund(address, amount)` 
- `waitForTx(txId)` to be confirmed

feat: testcontainers basic utility

---

crates/bvs-rewards/README.md
crates/bvs-rewards/README.mdx
docs/app/contracts/rewards/page.md
docs/app/contracts/rewards/page.mdx
docs/app/getting-started/_meta.ts
docs/app/getting-started/rewards/page.mdx
docs/app/page.mdx

feat: rewards docs

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

feat: add status to slashing request

---

examples/package.json
examples/squaring/README.mdx
examples/squaring/service/package.json
examples/squaring/service/src/contract.ts
examples/squaring/service/src/squaring.test.ts
examples/squaring/service/src/squaring.ts
modules/package.json
packages/testcontainers/src/container.test.ts
packages/testcontainers/src/container.ts
packages/testcontainers/src/satlayer.ts
pnpm-lock.yaml

chore(examples): squaring service

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

feat: store request_resolution in slash request

---

.github/workflows/ci.yml
.github/workflows/release.yml

As the title suggests, the entire workflow can benefit from this environment being set.

chore(workflows): set DOCKER_CACHE_FROM for all workflows

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/tests/integration_test.rs

chore: fix import

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs

The indexed map key of the `SLASH_REQUEST` is owned. Typically this is not that big of a problem for primitive type that live on stack. But `SlashRequestId` is a custom struct with pretty elaborate trait implementations. Having to clone just to read its value etc induce clone overhead. 
Closes SL-505

chore: indexed map key SlashRequestId be referenced instead of own value

---

packages/testcontainers/package.json
packages/testcontainers/src/container.ts
pnpm-lock.yaml

Additional utility to make it easier to test with `CosmWasmContainer`.

chore: additional utility for testcontainers

---

packages/testcontainers/package.json
packages/testcontainers/src/bvs.ts
packages/testcontainers/src/satlayer.test.ts
packages/testcontainers/src/satlayer.ts
pnpm-lock.yaml

feat: deploy tokenized vaults in testcontainers

---

packages/testcontainers/src/satlayer.ts

chore: update contracts codeId for tokenized vaults

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/src/state.rs
crates/bvs-vault-router/tests/integration_test.rs
docs/app/getting-started/slashing/page.mdx
modules/cosmwasm-schema/vault-router/schema.go
packages/cosmwasm-schema/vault-router.d.ts

fix: add 7 days const to request expiry

---

.github/workflows/release.yml

chore(release): publish additional crates for v2

---

packages/testcontainers/package.json
packages/testcontainers/src/bvs.ts
packages/testcontainers/src/satlayer.ts
pnpm-lock.yaml

- Add Rewards contract to test container
- refactor contract type to be generic

feat: add rewards to testcontainers

---

crates/bvs-guardrail/src/contract.rs
crates/bvs-guardrail/src/msg.rs
crates/bvs-pauser/src/contract.rs
crates/bvs-pauser/src/msg.rs
crates/bvs-registry/src/contract.rs
crates/bvs-rewards/src/contract.rs
crates/bvs-rewards/src/msg.rs
crates/bvs-vault-bank-tokenized/src/contract.rs
crates/bvs-vault-bank/src/contract.rs
crates/bvs-vault-cw20-tokenized/src/contract.rs
crates/bvs-vault-cw20/src/contract.rs
crates/bvs-vault-factory/src/contract.rs
crates/bvs-vault-factory/src/msg.rs

chore: documented all `pub fn migrate`

---

crates/bvs-rewards/src/merkle.rs
modules/cosmwasm-cli/cmd/rewards.go

fix: update rewards contract leaf hash to double hash

---

examples/squaring/README.mdx

chore(docs): example README typo

---

crates/bvs-vault-router/src/contract.rs
crates/bvs-vault-router/tests/integration_test.rs

chore: throw error when bips is zero

---

contracts/src/EmptyImpl.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYTestSuite.sol
contracts/test/SLAYVault.t.sol

feat: set up proxy pattern for immutable contract addresses

---

packages/cosmwasm-optimizer/bin.js

More customizability to extend cosmwasm-optimizer.

chore: cosmwasm-optimizer more customizability

---

packages/cosmwasm-schema-cli/README.md
packages/cosmwasm-schema-cli/package.json
packages/cosmwasm-schema-cli/schema-gen.mjs
pnpm-lock.yaml

chore: add cosmwasm-schema-cli to generate schema for any rust contract

---

contracts/src/EmptyImpl.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/src/SLAYVault.sol
contracts/src/SLAYVaultFactory.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYVault.t.sol
contracts/test/TestSuite.sol

chore: setup evm beacon pattern for Vault

---

.prettierignore

chore(workflows): ignore md,mdx from prettier to make docs edit easier

---

contracts/src/SLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

feat: SLAYRegistry service operator relationship

---

contracts/script/Deployment.s.sol
contracts/src/InitialImpl.sol
contracts/src/SLAYRegistry.sol
contracts/src/SLAYRouter.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/TestSuite.sol

feat: solidity contracts deployment scripts

---

.idea/satlayer-bvs.iml
contracts/src/SLAYRegistry.sol
contracts/src/SLAYVault.sol
contracts/src/SLAYVaultFactory.sol
contracts/src/interface/IERC7540.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/SLAYVault.t.sol
contracts/test/SLAYVaultFactory.t.sol

feat: erc-7540 async vault redeem 

---

contracts/src/SLAYRouter.sol
contracts/src/SLAYVaultFactory.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/src/interface/ISLAYRouter.sol
contracts/src/interface/ISLAYVaultFactory.sol
contracts/test/SLAYRouter.t.sol
contracts/test/SLAYVaultFactory.t.sol

- Add `ISLAYVaultFactory`
- Add `ISLAYRouter`
Closes SL-597
Closes SL-598

chore: add interface to Router and VaultFactory

---

.github/release-drafter.yml
.github/release-labeling.yml

chore(workflow): auto labeling for a/contracts

---

.github/release-drafter.yml

chore(workflows): auto categorize dependencies

---

contracts/src/Relationship.sol
contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

chore: move Registration logic to Relationship.sol

---

contracts/script/Deployment.s.sol
contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol
contracts/test/TestSuite.sol

feat: enable/disable slashing for service

---

contracts/src/Relationship.sol
contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

feat: max active relationship in evm registry

---

contracts/src/SLAYRegistry.sol
contracts/src/interface/ISLAYRegistry.sol
contracts/test/SLAYRegistry.t.sol

feat: timestamped slashing parameter query for a service operator pair

---

contracts/src/InitialImpl.sol
contracts/src/RelationshipV2.sol
contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYRegistryV2.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/src/interface/ISLAYVaultFactoryV2.sol
contracts/src/interface/ISLAYVaultV2.sol

Add missing NatSpec and update incorrect comments.

chore(docs): NatSpec comments for contracts

---

contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultFactoryV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/IERC7540.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYRouterV2.t.sol
contracts/test/SLAYVaultV2.t.sol

chore: contracts housekeeping and minor cleanup

---

contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYVaultV2.t.sol

feat: add slashLock to Vault

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/src/interface/ISLAYSlashingV2.sol
contracts/test/SLAYRouterV2.t.sol

Set up the basic foundation for slashing, with a simple ideal route.

chore: slashing request foundation

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYSlashingV2.sol

chore: refactor "non-null" checks for pending Slashing Requests

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol
contracts/test/SLAYRouterV2.t.sol

chore: use Payload calldata payload for requestSlashing

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/test/SLAYRouterV2.t.sol

- Adds finalize slashing to router
- adds Guardrail + guardrail voting
- Refactor error msg to be more reusable across fns
TODO:
Closes SL-581

feat: finalize slashing in router

---

contracts/test/SLAYRouterV2.t.sol

chore: tests for slashing request

---

contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYVaultV2.t.sol

chore: document and refactoring of SLAYVault

---

contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol
contracts/src/interface/ISLAYRouterV2.sol
contracts/test/SLAYRouterV2.t.sol

chore: document and refactor SLAYRouter

---

contracts/src/MerkleProof.sol

chore: document MerkleProof.sol

---

.github/actions/setup/action.yml
.github/workflows/slaynet.yml
contracts/foundry.toml
contracts/script/Deployment.s.sol

feat: CD of SLAY contracts to SLAYNet

---

contracts/src/SLAYRewardsV2.sol
contracts/src/interface/ISLAYRewardsV2.sol
contracts/test/MerkleProof.t.sol
contracts/test/SLAYRewardsV2.t.sol
contracts/test/TestSuiteV2.sol

feat: SLAYRewards for EVM

---

contracts/src/SLAYVaultV2.sol

chore: add whenNotPaused to vault fns

---

contracts/src/SLAYRewardsV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol

chore: fix forge lint warning

---

contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYVaultV2.sol
contracts/test/SLAYVaultV2.t.sol

Running snapshot diff against the base branch
Part of SL-639

chore(gas): remove public isWhitelisted fn from vault

---

contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/SLAYVaultV2.sol
contracts/src/interface/ISLAYRewardsV2.sol

chore: properly document access control

---

contracts/src/SLAYRegistryV2.sol

chore: minor gas optimization for setWithdrawalDelay

---

contracts/test/MerkleProof.t.sol

Part of the internal audit efforts. Add addtional test for merkle proof verification related solidity code concerning unbalanced and large trees.
Closes SL-646

chore: additional test cases for merkle proof

---

examples/evm/layerzero-dvn/.gitignore
examples/evm/layerzero-dvn/README.md
examples/evm/layerzero-dvn/foundry.toml
examples/evm/layerzero-dvn/layerzero-dvn.iml
examples/evm/layerzero-dvn/package.json
examples/evm/layerzero-dvn/remappings.txt
examples/evm/layerzero-dvn/src/configHelper.ts
examples/evm/layerzero-dvn/src/contracts/BVS.sol
examples/evm/layerzero-dvn/src/contracts/CustomDVN.sol
examples/evm/layerzero-dvn/src/contracts/SimpleOApp.sol
examples/evm/layerzero-dvn/src/contracts/interface/IBVS.sol
examples/evm/layerzero-dvn/src/dvnNode.ts
examples/evm/layerzero-dvn/src/lifecycle.test.ts
examples/evm/layerzero-dvn/src/lz.constant.ts
examples/evm/layerzero-dvn/src/operatorNode.ts
examples/evm/layerzero-dvn/tsconfig.json
examples/evm/layerzero-dvn/turbo.json
pnpm-lock.yaml

chore: LZ example with SL EVM Control Plane

---

packages/testcontainers/src/anvil-container.test.ts
packages/testcontainers/src/anvil-container.ts

chore: fix anvil mine interval

---

README.md

chore: update README.md to point to docs correctly

---

crates/bvs-library/src/slashing.rs
pnpm-lock.yaml

extra:
- fix broken lockfile
Closes SL-690

fix: cargo lint error due to elided lifetime

---

contracts/src/SLAYRegistryV2.sol
contracts/src/SLAYRouterV2.sol
contracts/src/interface/ISLAYRegistryV2.sol
contracts/src/interface/ISLAYRouterSlashingV2.sol
contracts/test/SLAYRegistryV2.t.sol
contracts/test/SLAYRouterV2.t.sol
docs/app/architecture/slashing/page.mdx

Closes SL-696
Closes SL-695
Closes SL-694
Closes SL-693
Closes SL-692

chore: fix advisory audit issues

---

contracts/README.md

chore(docs): document @satlayer/contracts

---

docs/app/cosmwasm/developer/integrating/page.mdx
docs/app/cosmwasm/developer/page.mdx
docs/app/evm/_meta.ts
docs/app/evm/developer/_meta.ts
docs/app/evm/developer/deploying/page.mdx
docs/app/evm/developer/installation/page.mdx
docs/app/evm/developer/integrating/page.mdx
docs/app/evm/developer/page.mdx

Misc:
- fixes some broken link on CW due to recent refactoring
Closes SL-684

chore: add integrating with EVM docs

---

contracts/script/Sepolia.sol

feat: basic lifecycle scripts for sepolia

---

examples/README.md

chore(docs): update README.md in examples

---

examples/evm/threshold-security/src/lifecycle.test.ts

1. fix the lifecycle test price

chore: fix threshold example + more comments

---

crates/README.md

chore(docs): updated BVS Vault Factory address
